name: PR CI

on: 
  pull_request:
    branches:
      - master

jobs:
  build_pr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: client install, build, and test
      working-directory: ./client
      run: |
        yarn install
        yarn lint
        yarn build
      env:
        CI: true
    - name: server install, build, and test
      working-directory: ./server
      run: |
        yarn install
        yarn lint
        yarn test
        yarn build
      env:
        CI: true
